name: API Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: execute tests
      # We explicitly trigger test-compile first to force verification of all required file resources
      run: mvn clean test-compile test -Dsuite=suite -Dmaven.test.failure.ignore=true

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: logs/

    - name: Publish TestNG Report
      if: always()
      uses: ScalableCapital/action-surefire-report@v2
      with:
        # Highlight-start
        # Targeted direct file path to bypass wildcard resolution failures
        report_paths: 'target/surefire-reports/testng-results.xml'
        # Highlight-end
