name: API Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: execute tests
      # Highlight-start
      # Matches your exact pom.xml property mapping while preventing build termination on failed assertions
      run: mvn clean test -Dsuite=suite -Dmaven.test.failure.ignore=true -X
      # Highlight-end

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: logs/

    - name: Publish TestNG Report
      if: always()
      uses: ScalableCapital/action-surefire-report@v2
      with:
        report_paths: '**/target/surefire-reports/testng-results.xml'
